# Start Working with Numpy Library

Importing the Numpy Library and put this Library as a Charactar ====> np ===> Best Practice  

In [2]:
import numpy as np

In [2]:
print("Hello NumPy")

Hello NumPy


In [3]:
print("This is a First Test ===> NumPy Library")

This is a First Test ===> NumPy Library


In [4]:
# How to make an array of the np object Method 

In [3]:
arr = np.arange(0 , 10)

In [4]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr = np.arange(0 , 10 , 2)

In [8]:
arr

array([0, 2, 4, 6, 8])

In [14]:
# Operations in Array

In [9]:
arr.max()

8

In [10]:
arr.min()

0

In [11]:
arr.argmax()

4

In [12]:
arr[arr.argmax()]

8

In [13]:
arr.min()

0

In [15]:
# Making Zeroes Array

In [19]:
np.zeros((2,2)) # ===> ((row , col))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [20]:
# Making the Ones Array

In [9]:
np.ones((5 , 6)) # ====> ((row , col))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [10]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [25]:
# Making Linspace Array ===> Give them them Start and End and it will get the Number between them in an Array 

In [12]:
np.linspace(0 , 20 , 10)

array([  0.        ,   2.22222222,   4.44444444,   6.66666667,
         8.88888889,  11.11111111,  13.33333333,  15.55555556,
        17.77777778,  20.        ])

In [43]:
# Making an Array of matrix of an Eye Which will have a Diagonal with One ===> Benefit in the Algebric Operations or Relation 

In [47]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [27]:
# making the Random Arrays

In [13]:
np.random.rand(2,2) # Get Random Numbers ===> From Gaussian Curve ===> Normal Distrbuition ==> Get Only Positive Numbers

array([[ 0.93234207,  0.48634999],
       [ 0.18341394,  0.98477156]])

In [14]:
np.random.randn(2 , 5)   # Get Random Numbers ==> From Normal Distrb. Curve ==> But get Positive and Negitive Numbers 

array([[ 0.64594297, -1.29414578, -0.66299747,  1.25642124,  0.72219254],
       [-0.33682181, -0.86931019,  1.23078863,  0.37720249, -2.0351088 ]])

In [15]:
np.random.randint(0,20)  # Get Random Numbers Between Two Numbers 

0

In [16]:
np.random.randint(0,20 , 100)  # Get one Hundred Record Betweeen the Start and End ===> ( Start , End , Size of Array )

array([ 8,  5, 18, 14, 18, 11, 19,  8,  1,  6, 16, 14, 12,  9,  6,  9, 17,
       15,  8, 19, 17, 12,  1,  1,  6, 17, 18, 18, 15,  7, 11, 10,  3, 14,
        1,  8,  8, 15, 13, 14,  8,  8,  2,  8, 13, 16, 14,  2,  7, 18, 19,
       14,  8, 15, 16,  2, 14, 16, 19, 12,  9, 13, 15,  1,  6, 19, 13,  6,
       13, 18, 17, 12, 15, 14, 12,  9,  9,  6, 11, 15, 18,  9, 18,  3,  6,
       10, 15, 11,  2, 17,  5,  0, 10,  3,  8, 18,  9, 15, 17, 11])

In [48]:
#Shaping the Array 

In [55]:
listArray = np.random.randint(0 , 20 , 50)

In [56]:
listArray

array([18, 11,  3, 18,  8, 16,  6,  5, 15, 11, 15, 15,  3, 10,  4,  1, 10,
        5, 15, 10, 12, 13, 19,  0, 11, 17,  5,  1,  5, 11, 14,  7, 10, 15,
        2,  3, 19,  7,  4,  9,  4,  4,  2, 18, 18,  9, 19,  2,  3, 12])

In [57]:
set(listArray)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}

In [61]:
listArray.reshape(5 , 10) # reshape(row , Col)  ===> row * col should Equals to the len(this.array)

array([[18, 11,  3, 18,  8, 16,  6,  5, 15, 11],
       [15, 15,  3, 10,  4,  1, 10,  5, 15, 10],
       [12, 13, 19,  0, 11, 17,  5,  1,  5, 11],
       [14,  7, 10, 15,  2,  3, 19,  7,  4,  9],
       [ 4,  4,  2, 18, 18,  9, 19,  2,  3, 12]])

In [62]:
listArray.dtype

dtype('int32')

In [64]:
listArray[listArray > 5]

array([18, 11, 18,  8, 16,  6, 15, 11, 15, 15, 10, 10, 15, 10, 12, 13, 19,
       11, 17, 11, 14,  7, 10, 15, 19,  7,  9, 18, 18,  9, 19, 12])

In [67]:
listArray.shape

(50,)

In [68]:
listArray.reshape(5,10)

array([[18, 11,  3, 18,  8, 16,  6,  5, 15, 11],
       [15, 15,  3, 10,  4,  1, 10,  5, 15, 10],
       [12, 13, 19,  0, 11, 17,  5,  1,  5, 11],
       [14,  7, 10, 15,  2,  3, 19,  7,  4,  9],
       [ 4,  4,  2, 18, 18,  9, 19,  2,  3, 12]])

In [72]:
listArray.shape

(50,)

In [74]:
#Sorting Any Array 

In [76]:
listArray.sort()

In [77]:
listArray

array([ 0,  1,  1,  2,  2,  2,  3,  3,  3,  3,  4,  4,  4,  4,  5,  5,  5,
        5,  6,  7,  7,  8,  9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12,
       13, 14, 15, 15, 15, 15, 15, 16, 17, 18, 18, 18, 18, 19, 19, 19])

# Operation in NumPy Array 

 1. Array with Array 
 2. Array with Scalars
 3. Universal Function with Arrays

In [78]:
arr = np.arange(0 , 20)

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [80]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [81]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
arr / arr 

C:\Users\Mohamed\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [83]:
1 / arr 

C:\Users\Mohamed\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ,  0.09090909,  0.08333333,  0.07692308,  0.07142857,
        0.06666667,  0.0625    ,  0.05882353,  0.05555556,  0.05263158])

In [84]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [85]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04,   5.98741417e+04,
         1.62754791e+05,   4.42413392e+05,   1.20260428e+06,
         3.26901737e+06,   8.88611052e+06,   2.41549528e+07,
         6.56599691e+07,   1.78482301e+08])

In [86]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462])

In [87]:
np.log(arr)

C:\Users\Mohamed\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509,  2.39789527,  2.48490665,  2.56494936,  2.63905733,
        2.7080502 ,  2.77258872,  2.83321334,  2.89037176,  2.94443898])

In [1]:
# Make Numpy Review

In [2]:
import numpy as np

In [3]:
# Make a Numpy Array

In [6]:
first = np.arange(0,10)

In [7]:
first

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# get the Max Value

In [15]:
# Get the index of the Max value

In [17]:
np.argmax(first)

9

In [18]:
# Get the Max Value itself 

In [19]:
np.max(first)

9

In [20]:
# Get Min and Min Index

In [21]:
np.argmin(first)

0

In [22]:
np.min(first)

0

In [23]:
# Make Random Array

In [26]:
second = np.random.rand(10)

In [27]:
second

array([ 0.47811973,  0.41428989,  0.84803101,  0.26007498,  0.34973796,
        0.03880971,  0.07735934,  0.35275358,  0.32555591,  0.31782536])

In [31]:
# random with Negtive and Positive Numbers ==> From Gussian Curve

In [32]:
third = np.random.randn(10)

In [33]:
third

array([ 1.82646624,  1.24439235,  0.5736498 , -0.76380487, -0.48322757,
        0.99119912,  0.08793477, -0.18061696,  0.15977015, -2.18270565])

In [41]:
fourth = np.random.randint(0 ,20 , 10)

In [42]:
fourth

array([ 5,  0, 11,  7, 19, 12,  8,  8,  3,  4])

In [43]:
# Make a set 

In [44]:
new__Set = { 1 , 10 , 5 , 5 , 8 , 2 , 3 , 2 }

In [45]:
# Set Take Only Unique Values

In [46]:
new__Set

{1, 2, 3, 5, 8, 10}

In [52]:
# Make Linspace  ==> Take Start , End , number of diff.

In [53]:
five = np.linspace( 0 , 20 , 15)

In [54]:
five

array([  0.        ,   1.42857143,   2.85714286,   4.28571429,
         5.71428571,   7.14285714,   8.57142857,  10.        ,
        11.42857143,  12.85714286,  14.28571429,  15.71428571,
        17.14285714,  18.57142857,  20.        ])

In [55]:
fourth.sort()

In [56]:
fourth

array([ 0,  3,  4,  5,  7,  8,  8, 11, 12, 19])

In [58]:
fourth.size

10

In [59]:
# Universal Functions 

In [60]:
np.sin(fourth)

array([ 0.        ,  0.14112001, -0.7568025 , -0.95892427,  0.6569866 ,
        0.98935825,  0.98935825, -0.99999021, -0.53657292,  0.14987721])

In [61]:
np.cos(fourth)

array([ 1.        , -0.9899925 , -0.65364362,  0.28366219,  0.75390225,
       -0.14550003, -0.14550003,  0.0044257 ,  0.84385396,  0.98870462])

In [62]:
np.log(fourth)

C:\Users\Mohamed\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  1.09861229,  1.38629436,  1.60943791,  1.94591015,
        2.07944154,  2.07944154,  2.39789527,  2.48490665,  2.94443898])

In [64]:
np.exp(fourth)

array([  1.00000000e+00,   2.00855369e+01,   5.45981500e+01,
         1.48413159e+02,   1.09663316e+03,   2.98095799e+03,
         2.98095799e+03,   5.98741417e+04,   1.62754791e+05,
         1.78482301e+08])

In [65]:
# End of Review 1 