# Start Working with Pandas

In [1]:
print("Welcome To Pandas for Data Analysis and Data Visualization")

Welcome To Pandas for Data Analysis and Data Visualization


In [13]:
import numpy as np

In [14]:
#Checking for the numpy Library

In [6]:
numArray = np.arange(0,10)

In [7]:
numArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
numArrayRandom = np.random.randint(0,20,20)

In [9]:
numArrayRandom

array([11,  5,  5,  3,  8,  6, 19, 11, 10, 15, 16, 16,  2, 16, 10, 18, 12,
       16, 12,  6])

In [10]:
len(numArrayRandom)

20

In [12]:
len(numArray)

10

In [15]:
# Start for the Series Pandas Object

In [17]:
import pandas as pd

In [19]:
newList = ['a','b','c']
numList = np.arange(0,3)
dic = {'a':0 , 'b':1 , 'c':2}

In [24]:
seriesObject = pd.Series(data = newList) #Series ===> data ===> List ,, ===> index ===> By Default ==> 0 ===> inf. , or pass list

In [25]:
seriesObject

0    a
1    b
2    c
dtype: object

In [26]:
seriesObject = pd.Series(numList , newList)

In [27]:
seriesObject

a    0
b    1
c    2
dtype: int32

In [29]:
seriesObject['a'] # We call by the Value of the Labels not the Data 

0

In [30]:
numList

array([0, 1, 2])

In [31]:
# Start with the Data Frames

In [32]:
randArray = np.random.randint(0,20,20)

In [42]:
randArray.reshape(5,4)

array([[ 3, 16,  4,  9],
       [11,  4,  8, 19],
       [12,  2,  9,  8],
       [ 6,  2, 19,  3],
       [ 3, 13,  6,  0]])

In [34]:
randArray.

(20,)

In [35]:
col = ['A' , 'B' , 'C' , 'D']

In [36]:
rows = [1 , 2 , 3 , 4 , 5]

In [45]:
dataFrames = pd.DataFrame(np.random.randn(5,4), rows , col) 

In [46]:
dataFrames

A         B         C         D
1 -0.339545  0.198696 -0.819566  1.769288
2 -0.421064 -1.211145 -0.713322  1.458623
3 -1.288153 -1.477760 -0.558187 -0.498091
4  0.592058 -0.865973 -2.380285  0.871634
5  0.918776 -0.289275 -0.655583  0.857204

In [47]:
dataFrames['A']

1   -0.339545
2   -0.421064
3   -1.288153
4    0.592058
5    0.918776
Name: A, dtype: float64

In [48]:
dataFrames[['B' , 'D']]

B         D
1  0.198696  1.769288
2 -1.211145  1.458623
3 -1.477760 -0.498091
4 -0.865973  0.871634
5 -0.289275  0.857204

In [49]:
#Add New Rows 

In [50]:
dataFrames['E'] = dataFrames['A'] + dataFrames['C']

In [51]:
dataFrames

A         B         C         D         E
1 -0.339545  0.198696 -0.819566  1.769288 -1.159111
2 -0.421064 -1.211145 -0.713322  1.458623 -1.134386
3 -1.288153 -1.477760 -0.558187 -0.498091 -1.846340
4  0.592058 -0.865973 -2.380285  0.871634 -1.788227
5  0.918776 -0.289275 -0.655583  0.857204  0.263194

In [52]:
# Drop a Row or Col

In [54]:
dataFrames.drop('A',axis = 1) # this is just for the First Time or Locally not for ever 

B         C         D         E
1  0.198696 -0.819566  1.769288 -1.159111
2 -1.211145 -0.713322  1.458623 -1.134386
3 -1.477760 -0.558187 -0.498091 -1.846340
4 -0.865973 -2.380285  0.871634 -1.788227
5 -0.289275 -0.655583  0.857204  0.263194

In [55]:
dataFrames

A         B         C         D         E
1 -0.339545  0.198696 -0.819566  1.769288 -1.159111
2 -0.421064 -1.211145 -0.713322  1.458623 -1.134386
3 -1.288153 -1.477760 -0.558187 -0.498091 -1.846340
4  0.592058 -0.865973 -2.380285  0.871634 -1.788227
5  0.918776 -0.289275 -0.655583  0.857204  0.263194

In [56]:
# Calling the Cols 

In [60]:
dataFrames.loc[1] # BY Label Names

A   -0.339545
B    0.198696
C   -0.819566
D    1.769288
E   -1.159111
Name: 1, dtype: float64

In [61]:
dataFrames.iloc[2]  # By the Indexing from 0 ====> inf.

A   -1.288153
B   -1.477760
C   -0.558187
D   -0.498091
E   -1.846340
Name: 3, dtype: float64

In [63]:
dataFrames.loc[[1 , 2],['A' , 'D']]   # dataFrames.loc[[col] , [rows]]

A         D
1 -0.339545  1.769288
2 -0.421064  1.458623

In [64]:
# New Operations with Pandas 

In [68]:
# Conditional Operational

In [69]:
dataFrames

A         B         C         D         E
1 -0.339545  0.198696 -0.819566  1.769288 -1.159111
2 -0.421064 -1.211145 -0.713322  1.458623 -1.134386
3 -1.288153 -1.477760 -0.558187 -0.498091 -1.846340
4  0.592058 -0.865973 -2.380285  0.871634 -1.788227
5  0.918776 -0.289275 -0.655583  0.857204  0.263194

In [66]:
dataFrames > 0

A      B      C      D      E
1  False   True  False   True  False
2  False  False  False   True  False
3  False  False  False  False  False
4   True  False  False   True  False
5   True  False  False   True   True

In [67]:
dataFrames[dataFrames > 0]

A         B   C         D         E
1       NaN  0.198696 NaN  1.769288       NaN
2       NaN       NaN NaN  1.458623       NaN
3       NaN       NaN NaN       NaN       NaN
4  0.592058       NaN NaN  0.871634       NaN
5  0.918776       NaN NaN  0.857204  0.263194

In [70]:
dataFrames['A'] > 0   

1    False
2    False
3    False
4     True
5     True
Name: A, dtype: bool

In [73]:
dataFrames[dataFrames['A'] > 0]   # Will show all rows except to the ones that has False in this ^^^^ 

A         B         C         D         E
4  0.592058 -0.865973 -2.380285  0.871634 -1.788227
5  0.918776 -0.289275 -0.655583  0.857204  0.263194

In [74]:
newData = dataFrames[dataFrames['B'] > 0]

In [75]:
newData

A         B         C         D         E
1 -0.339545  0.198696 -0.819566  1.769288 -1.159111

In [76]:
newData['B']

1    0.198696
Name: B, dtype: float64

In [82]:
dataFrames[(dataFrames['A'] >0) & (dataFrames['D'] > 0)]

A         B         C         D         E
4  0.592058 -0.865973 -2.380285  0.871634 -1.788227
5  0.918776 -0.289275 -0.655583  0.857204  0.263194

# Start for the MultiIndexing Topics

In [92]:
outside = ['G1' , 'G1' , 'G2' , 'G2' , 'G3' , 'G3']
inside = [ 1 , 2 , 1 ,2 , 1 ,2]
hier_index = list(zip(outside , inside))
hier_index = pd.MultiIndex.from_tuples(hier_index) # Making the Indexing for the Groups

In [87]:
hier_index

MultiIndex(levels=[['G1', 'G2', 'G3'], [1, 2]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [93]:
newData = pd.DataFrame(np.random.randn(6 , 3) , hier_index,['A' , 'B' , 'C'])  # Making the DaraFrames

In [90]:
newData

A         B         C
G1 1 -0.484380 -0.618422 -0.646845
   2 -0.109304  0.701431  0.050914
G2 1  0.902403  1.481875  0.944480
   2  1.228704  0.723044 -2.044432
G3 1 -0.471627 -2.152310 -0.519344
   2 -1.731793 -0.497116  1.805819

In [94]:
newData.loc['G1']

A         B         C
1 -0.539131 -1.433092 -0.490967
2  0.420213 -0.086473 -0.269890

In [95]:
newData.index.names = ['Groups' , 'Numbers']

In [100]:
newData

A         B         C
Groups Numbers                              
G1     1       -0.539131 -1.433092 -0.490967
       2        0.420213 -0.086473 -0.269890
G2     1        1.108830  0.648052 -0.399212
       2        0.785614  0.292049 -1.318991
G3     1        1.172588 -1.385039  1.586162
       2       -1.173093  0.455573  2.555750

In [101]:
# Allocate the Rows and cols in the DataFrame

In [97]:
newData.loc['G1'].loc[2]['C']   

-0.269889812952948

In [98]:
newData.loc['G2'].loc[1]['B']

0.64805203677584633

In [99]:
newData.loc['G3'].loc[2]['A']

-1.1730927300855358

In [103]:
newData.xs(2,level='Numbers') # xs ===> Cross Sections 

A         B         C
Groups                              
G1      0.420213 -0.086473 -0.269890
G2      0.785614  0.292049 -1.318991
G3     -1.173093  0.455573  2.555750

# Missing Data Sections

In [1]:
# We Mean By Missing Data to Nan Data

In [2]:
import numpy as np
import pandas as pd

In [3]:
dic = {'A':[1 , 2 ,3] , 'B':[1,np.nan,2] ,'C':[np.nan , 2 ,np.nan]}

In [4]:
data = pd.DataFrame(dic)

In [5]:
data

A    B    C
0  1  1.0  NaN
1  2  NaN  2.0
2  3  2.0  NaN

In [108]:
#Drop NaN Data from the Whole Table

In [111]:
data.dropna(axis=1)

A
0  1
1  2
2  3

In [112]:
data.fillna(value='New Data')

A         B         C
0  1         1  New Data
1  2  New Data         2
2  3         2  New Data

In [117]:
data.dropna()

Empty DataFrame
Columns: [A, B, C]
Index: []

# Merging and Joining & GroupBy 

In [171]:
# Make a Dictionary and Make it like a DataFrame

# GroupBy Function 

In [119]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [120]:
newData = pd.DataFrame(data)

In [121]:
newData

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [122]:
# Start for the Grouping

In [131]:
data_com = newData.groupby('Company') # allocate the position in Memory

In [132]:
# Make the Operation in this Field

In [133]:
data_com.sum()

Sales
Company       
FB         593
GOOG       320
MSFT       464

In [134]:
data_com.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [135]:
data_com.std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [137]:
data_com.describe()   # Give us the Whole Info in every Grouped Row 

Sales
Company                  
FB      count    2.000000
        mean   296.500000
        std     75.660426
        min    243.000000
        25%    269.750000
        50%    296.500000
        75%    323.250000
        max    350.000000
GOOG    count    2.000000
        mean   160.000000
        std     56.568542
        min    120.000000
        25%    140.000000
        50%    160.000000
        75%    180.000000
        max    200.000000
MSFT    count    2.000000
        mean   232.000000
        std    152.735065
        min    124.000000
        25%    178.000000
        50%    232.000000
        75%    286.000000
        max    340.000000

In [139]:
data_com.describe().transpose()

count   mean         std    min    25%    50%    75%    max
Sales    2.0  232.0  152.735065  124.0  178.0  232.0  286.0  340.0

In [140]:
data_com.describe().transpose()['MSFT']

count   mean         std    min    25%    50%    75%    max
Sales    2.0  232.0  152.735065  124.0  178.0  232.0  286.0  340.0

In [141]:
data_com.describe().transpose()['FB']

count   mean        std    min     25%    50%     75%    max
Sales    2.0  296.5  75.660426  243.0  269.75  296.5  323.25  350.0

In [142]:
data_com.describe().transpose()['GOOG']

count   mean        std    min    25%    50%    75%    max
Sales    2.0  160.0  56.568542  120.0  140.0  160.0  180.0  200.0

In [143]:
data_com.max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [144]:
data_com.min()

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [145]:
#-----------------------------------------------------------------------------#

In [146]:
# Start with the Merging and Joining 

In [149]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [151]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [152]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [148]:
pd.concat([df1,df2])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [153]:
pd.concat([df1,df2],axis=1)   # to rows 

A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7

# Merging 

In [154]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})    

In [155]:
left

A   B key
0  A0  B0  K0
1  A1  B1  K1
2  A2  B2  K2
3  A3  B3  K3

In [156]:
right

C   D key
0  C0  D0  K0
1  C1  D1  K1
2  C2  D2  K2
3  C3  D3  K3

In [160]:
pd.merge(left , right , how='inner' , on='key')  # Merge By the Common col or Row

A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3

In [161]:
pd.merge(left , right , how='outer' , on='key')

A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3

# Joining

In [162]:
# Example of dectionaries

In [165]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [167]:
left

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [168]:
right

C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [164]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [170]:
# --- End of the Merging , Joining and Concatinating  -------- #

# Operations 

In [172]:
df1


A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [173]:
df1.isnull()

A      B      C      D
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False

In [174]:
df1.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [175]:
df1.sort_values('D')

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [179]:
df1['A']

0    A0
1    A1
2    A2
3    A3
Name: A, dtype: object

In [190]:
d = {'k1':[1,4,6],'k2':[1,8,10],'k3':[5,8,20]}

In [191]:
d

{'k1': [1, 4, 6], 'k2': [1, 8, 10], 'k3': [5, 8, 20]}

In [192]:
data = pd.DataFrame(d)

In [193]:
data

k1  k2  k3
0   1   1   5
1   4   8   8
2   6  10  20

In [194]:
data['k1']

0    1
1    4
2    6
Name: k1, dtype: int64

In [195]:
data['k1'].apply(lambda x:x **2)

0     1
1    16
2    36
Name: k1, dtype: int64

# Input Data and OutPut 

In [196]:
print('Welcome to Input Data and Output Data Section in this Course')

Welcome to Input Data and Output Data Section in this Course


In [197]:
# Read Data from CSV Files 

In [198]:
data_csv = pd.read_csv('example')

In [199]:
data_csv

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [200]:
# Write in another csv File

In [202]:
data_csv.to_csv('My_new',index=False)

In [203]:
# Read Data from the Excel Files 

In [204]:
data_excel = pd.read_excel('Excel_Sample.xlsx')

In [205]:
data_excel

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [206]:
# Write inside another Excel File

In [208]:
data_excel.to_excel('new.xlsx',sheet_name='Shorbagy')

In [209]:
# -------------------------- End to the Operations and Input and Output Data from Files ----------------------------#